# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build

on: [push]

permissions:
  contents: write   # still needed for artifact steps

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .        # directory of your LaTeX files
      FILE: cv      # main .tex file name without extension
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Build CV with LaTeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}

      - name: Move PDF to artifacts
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/

      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: github_artifacts

      - name: Move to deploy dir
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy

      - name: Deploy PDF to build branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}   # ✅ PAT instead of GITHUB_TOKEN
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true

  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy index.html and CNAME to build branch
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME

